# In the following code:
### Q1: Neural Network was created with initialization of weights, it takes 2 inputs, 1 hidden layer with 3 neurons, 1 output
### Q2: Forward Propogation was implemented
### Q3: Mean absolute error was used as a Loss Function
### Q4: Learning rate was set to 1 as I wanted fast convergence due to my small dataset, 50000 epochs were used with batch size equal to 1
### Q5: I trained the NN with AND gate dataset
### Q6: I printed Weights after every 1000 epochs
### Q7: I tested the NN with the AND gate dataset and got very good accuracy

In [2]:
import numpy as np

# AND gate dataset
X = np.array(([1,0], [0,1], [0, 0], [1,1]), dtype=float)
y = np.array(([0], [0], [0], [1]), dtype=float)

class NeuralNetwork(object):
    def __init__(self):
        # Parameters
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        
        # Initialization of weights
        self.W1 = np.random.randn(self.inputSize, self.hiddenSize) # (3x2) weight matrix from input to hidden layer
        self.W2 = np.random.randn(self.hiddenSize, self.outputSize) # (3x1) weight matrix from hidden to output layer
        
    # Forward propogation through the network
    def feedForward(self, X):    
        self.z = np.dot(X, self.W1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2, self.W2)
        output = self.sigmoid(self.z3)
        return output
        
    # Activation Function
    def sigmoid(self, s, deriv=False):
        if (deriv == True):
            return s * (1 - s)
        return 1/(1 + np.exp(-s))
    
    # Backward propogate through the network
    def backward(self, X, y, output):
        # Loss Function
        self.output_error = y - output
        self.output_delta = self.output_error * self.sigmoid(output, deriv=True)
        
        self.z2_error = self.output_delta.dot(self.W2.T)
        self.z2_delta = self.z2_error * self.sigmoid(self.z2, deriv=True)
        
        # Ajusting first set (input -> hidden) weights, Learning rate = 1
        self.W1 += X.T.dot(self.z2_delta) 
        # Adjusting second set (hidden -> output) weights, Learning rate = 1
        self.W2 += self.z2.T.dot(self.output_delta)
        
    def train(self, X, y):
        output = self.feedForward(X)
        self.backward(X, y, output)
        
NN = NeuralNetwork()

# Number of epochs = 50000, Batch size = 1
for i in range(50000):
    if (i % 1000 == 0):
        print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
        # Visualization of weights after every 1000 epochs
        print("Weights 1: ", NN.W1)
        print("Weights 2: ", NN.W2)
    NN.train(X, y)
        
print("Input: " + str(X))
print("Actual Output: " + str(list(y)))
print("Loss: " + str(np.mean(np.square(y - NN.feedForward(X)))))
print("Predicted Output: " + str(list(NN.feedForward(X))))

Loss: 0.2133009643607874
Weights 1:  [[-0.95582133 -1.72386724  0.18804933]
 [ 1.22847233  0.76095939  1.09030045]]
Weights 2:  [[-1.66126103]
 [-0.12800517]
 [-1.07289274]]
Loss: 0.0014205426205617469
Weights 1:  [[ 0.912942   -5.35532708 -0.42453909]
 [-3.86258503  2.12925181  3.0736801 ]]
Weights 2:  [[-6.84876362]
 [-7.32852187]
 [ 3.7191189 ]]
Loss: 0.000559497662783821
Weights 1:  [[ 1.13474894 -5.79053534 -0.53795275]
 [-4.27201587  2.36678869  3.31768815]]
Weights 2:  [[-7.20131281]
 [-8.2098955 ]
 [ 4.13890632]]
Loss: 0.00034218094575906154
Weights 1:  [[ 1.24143248 -6.00203313 -0.60234972]
 [-4.47099373  2.48078542  3.4473532 ]]
Weights 2:  [[-7.38498225]
 [-8.67227326]
 [ 4.36112385]]
Loss: 0.0002449145050975811
Weights 1:  [[ 1.31029132 -6.13970899 -0.64770148]
 [-4.60023324  2.55463283  3.53606181]]
Weights 2:  [[-7.5092877 ]
 [-8.98635025]
 [ 4.51269094]]
Loss: 0.000190116101047925
Weights 1:  [[ 1.36056628 -6.24091132 -0.68278221]
 [-4.69501807  2.60876502  3.60352899]]


Loss: 1.7749064508145376e-05
Weights 1:  [[ 1.76611335 -7.08280029 -1.03011809]
 [-5.47247356  3.05527739  4.24310233]]
Weights 2:  [[ -8.47415244]
 [-11.45609613]
 [  5.71568346]]
Loss: 1.735803970658196e-05
Weights 1:  [[ 1.76945999 -7.08994121 -1.03346251]
 [-5.47896817  3.05903851  4.2491308 ]]
Weights 2:  [[ -8.48229442]
 [-11.47715145]
 [  5.72599664]]
Loss: 1.6983717413065972e-05
Weights 1:  [[ 1.77272815 -7.09691746 -1.03673578]
 [-5.48531131  3.06271246  4.25502983]]
Weights 2:  [[ -8.49026206]
 [-11.4977585 ]
 [  5.73609093]]
Loss: 1.6625054054561267e-05
Weights 1:  [[ 1.7759213  -7.10373619 -1.03994083]
 [-5.49150961  3.06630304  4.26080483]]
Weights 2:  [[ -8.49806266]
 [-11.51793595]
 [  5.74597543]]
Input: [[1. 0.]
 [0. 1.]
 [0. 0.]
 [1. 1.]]
Actual Output: [array([0.]), array([0.]), array([0.]), array([1.])]
Loss: 1.628109102514108e-05
Predicted Output: [array([0.00305767]), array([0.00456635]), array([0.00078906]), array([0.99414331])]
